// Code generated by mockery v2.12.1. DO NOT EDIT.

package mocks

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"
)

// IHopeResponder is an autogenerated mock type for the IHopeResponder type
type IHopeResponder struct {
	mock.Mock
}

// Activate provides a mock function with given fields:
func (_m *IHopeResponder) Activate() {
	_m.Called()
}

// NewIHopeResponder creates a new instance of IHopeResponder. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewIHopeResponder(t testing.TB) *IHopeResponder {
	mock := &IHopeResponder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
