// Code generated by mockery v2.12.1. DO NOT EDIT.

package mocks

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"
)

// IHopeHandler is an autogenerated mock type for the IHopeHandler type
type IHopeHandler struct {
	mock.Mock
}

// Handle provides a mock function with given fields: hope
func (_m *IHopeHandler) Handle(hope []byte) []byte {
	ret := _m.Called(hope)

	var r0 []byte
	if rf, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = rf(hope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	return r0
}

// NewIHopeHandler creates a new instance of IHopeHandler. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewIHopeHandler(t testing.TB) *IHopeHandler {
	mock := &IHopeHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
