// Code generated by mockery v2.12.1. DO NOT EDIT.

package mocks

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"
)

// IFeature is an autogenerated mock type for the IFeature type
type IFeature struct {
	mock.Mock
}

// Run provides a mock function with given fields:
func (_m *IFeature) Run() {
	_m.Called()
}

// NewIFeature creates a new instance of IFeature. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewIFeature(t testing.TB) *IFeature {
	mock := &IFeature{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
