// Code generated by mockery v2.12.1. DO NOT EDIT.

package mocks

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"
)

// IIdentity is an autogenerated mock type for the IIdentity type
type IIdentity struct {
	mock.Mock
}

// Id provides a mock function with given fields:
func (_m *IIdentity) Id() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewIIdentity creates a new instance of IIdentity. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewIIdentity(t testing.TB) *IIdentity {
	mock := &IIdentity{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
