// Code generated by mockery v2.12.1. DO NOT EDIT.

package mocks

import (
	interfaces "github.com/rgfaber/go-vesca/sdk/interfaces"
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// IEventHandler is an autogenerated mock type for the IEventHandler type
type IEventHandler struct {
	mock.Mock
}

// Activate provides a mock function with given fields: _a0
func (_m *IEventHandler) Activate(_a0 func(interfaces.IEvt)) {
	_m.Called(_a0)
}

// NewIEventHandler creates a new instance of IEventHandler. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewIEventHandler(t testing.TB) *IEventHandler {
	mock := &IEventHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
