// Code generated by mockery v2.12.1. DO NOT EDIT.

package mocks

import (
	interfaces "github.com/rgfaber/go-vesca/sdk/interfaces"
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// IEvt is an autogenerated mock type for the IEvt type
type IEvt struct {
	mock.Mock
}

// AggregateId provides a mock function with given fields:
func (_m *IEvt) AggregateId() interfaces.IIdentity {
	ret := _m.Called()

	var r0 interfaces.IIdentity
	if rf, ok := ret.Get(0).(func() interfaces.IIdentity); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.IIdentity)
		}
	}

	return r0
}

// TraceId provides a mock function with given fields:
func (_m *IEvt) TraceId() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewIEvt creates a new instance of IEvt. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewIEvt(t testing.TB) *IEvt {
	mock := &IEvt{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
