// Code generated by mockery v2.12.1. DO NOT EDIT.

package mocks

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"
)

// IFact is an autogenerated mock type for the IFact type
type IFact struct {
	mock.Mock
}

// AggregateId provides a mock function with given fields:
func (_m *IFact) AggregateId() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// TraceId provides a mock function with given fields:
func (_m *IFact) TraceId() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewIFact creates a new instance of IFact. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewIFact(t testing.TB) *IFact {
	mock := &IFact{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
