// Code generated by mockery v2.12.1. DO NOT EDIT.

package mocks

import (
	interfaces "github.com/rgfaber/go-vesca/sdk/interfaces"
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// IHopeDeserializer is an autogenerated mock type for the IHopeDeserializer type
type IHopeDeserializer struct {
	mock.Mock
}

// Deserialize provides a mock function with given fields: _a0
func (_m *IHopeDeserializer) Deserialize(_a0 []byte) interfaces.IHope {
	ret := _m.Called(_a0)

	var r0 interfaces.IHope
	if rf, ok := ret.Get(0).(func([]byte) interfaces.IHope); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.IHope)
		}
	}

	return r0
}

// NewIHopeDeserializer creates a new instance of IHopeDeserializer. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewIHopeDeserializer(t testing.TB) *IHopeDeserializer {
	mock := &IHopeDeserializer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
