// Code generated by mockery v2.12.1. DO NOT EDIT.

package mocks

import (
	interfaces "github.com/rgfaber/go-vesca/sdk/interfaces"
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// IFactSerializer is an autogenerated mock type for the IFactSerializer type
type IFactSerializer struct {
	mock.Mock
}

// Serialize provides a mock function with given fields: fact
func (_m *IFactSerializer) Serialize(fact interfaces.IFact) ([]byte, error) {
	ret := _m.Called(fact)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(interfaces.IFact) []byte); ok {
		r0 = rf(fact)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interfaces.IFact) error); ok {
		r1 = rf(fact)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIFactSerializer creates a new instance of IFactSerializer. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewIFactSerializer(t testing.TB) *IFactSerializer {
	mock := &IFactSerializer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
