// Code generated by mockery v2.12.1. DO NOT EDIT.

package mocks

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"
)

// IFactEmitter is an autogenerated mock type for the IFactEmitter type
type IFactEmitter struct {
	mock.Mock
}

// Activate provides a mock function with given fields:
func (_m *IFactEmitter) Activate() {
	_m.Called()
}

// NewIFactEmitter creates a new instance of IFactEmitter. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewIFactEmitter(t testing.TB) *IFactEmitter {
	mock := &IFactEmitter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
