// Code generated by mockery v2.12.1. DO NOT EDIT.

package mocks

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"
)

// IHope is an autogenerated mock type for the IHope type
type IHope struct {
	mock.Mock
}

// AggregateId provides a mock function with given fields:
func (_m *IHope) AggregateId() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// TraceId provides a mock function with given fields:
func (_m *IHope) TraceId() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewIHope creates a new instance of IHope. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewIHope(t testing.TB) *IHope {
	mock := &IHope{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
