// Code generated by mockery v2.12.1. DO NOT EDIT.

package mocks

import (
	interfaces "github.com/rgfaber/go-vesca/sdk/interfaces"
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// IHopeRequester is an autogenerated mock type for the IHopeRequester type
type IHopeRequester struct {
	mock.Mock
}

// Request provides a mock function with given fields: _a0
func (_m *IHopeRequester) Request(_a0 interfaces.IHope) (interfaces.IFbk, error) {
	ret := _m.Called(_a0)

	var r0 interfaces.IFbk
	if rf, ok := ret.Get(0).(func(interfaces.IHope) interfaces.IFbk); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.IFbk)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(interfaces.IHope) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIHopeRequester creates a new instance of IHopeRequester. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewIHopeRequester(t testing.TB) *IHopeRequester {
	mock := &IHopeRequester{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
