// Code generated by mockery v2.12.1. DO NOT EDIT.

package mocks

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"
)

// ITopic is an autogenerated mock type for the ITopic type
type ITopic struct {
	mock.Mock
}

// Topic provides a mock function with given fields:
func (_m *ITopic) Topic() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewITopic creates a new instance of ITopic. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewITopic(t testing.TB) *ITopic {
	mock := &ITopic{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
