package config

const (
	GO_VESCA_NATS_URL        = "GO_VESCA_NATS_URL"
	GO_VESCA_NATS_USER       = "GO_VESCA_NATS_USER"
	GO_VESCA_NATS_PWD        = "GO_VESCA_NATS_PWD"
	GO_VESCA_TH_SENSOR_ID    = "GO_VESCA_TH_SENSOR_ID"
	GO_VESCA_TH_SENSOR_NAME  = "GO_VESCA_TH_SENSOR_NAME"
	GO_VESCA_GREENHOUSE_ID   = "GO_VESCA_GREENHOUSE_ID"
	GO_VESCA_GREENHOUSE_NAME = "GO_VESCA_GREENHOUSE_NAME"
)
