// Code generated by mockery v2.12.1. DO NOT EDIT.

package mocks

import (
	testing "testing"

	mock "github.com/stretchr/testify/mock"
)

// INatsConfig is an autogenerated mock type for the INatsConfig type
type INatsConfig struct {
	mock.Mock
}

// NATSPwd provides a mock function with given fields:
func (_m *INatsConfig) NATSPwd() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NATSUrl provides a mock function with given fields:
func (_m *INatsConfig) NATSUrl() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NATSUser provides a mock function with given fields:
func (_m *INatsConfig) NATSUser() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewINatsConfig creates a new instance of INatsConfig. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewINatsConfig(t testing.TB) *INatsConfig {
	mock := &INatsConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
